const projectsData = [
  {
    title: "HOTEL W UŚCIU GORLICKIM",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=199nVosWkwZgyPwjJdL4VzIDE1g9-f-ES",
      "http://drive.google.com/uc?export=view&id=105xQyORtcvQ10ad4KP4iDVNxrWPif2ZN",
      "http://drive.google.com/uc?export=view&id=1IYXkPKEB94xsUxjk4v9ngmTjFR0MWeoh",
      "http://drive.google.com/uc?export=view&id=1YZYO_432IvYApa09wjmwKH-bnlL3EzCR",
    ],
  },
  {
    title: "REZYDENCJA W TANZANII",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=13COFz51ev94mExSHDBeQO41gZ2VZK5bY",
      "http://drive.google.com/uc?export=view&id=11pkiz6ExWiQ-ftZJWakYkmvfuilPRpBf",
      "http://drive.google.com/uc?export=view&id=17LObnRMQ5BJtjmJmWIVJixHpbtnpzojl ",
      "http://drive.google.com/uc?export=view&id=19zuUlS0TomM0mDyZk_iYBVvNruz365XL ",
      "http://drive.google.com/uc?export=view&id=1OKWIjxjwiH7NxN7B8lATYa3pByn0nSGC",
      "http://drive.google.com/uc?export=view&id=1PVeg4oAs3eFtSFa5H4_yZfRQ1c1R_hLA ",
      "http://drive.google.com/uc?export=view&id=1YS5Qa1u1lICAASSNvOs0YWeCmDy8R8QN",
      "http://drive.google.com/uc?export=view&id=1k2AGZJPgw0xRaFoI6FTQH6lBPri76BTj",
      "http://drive.google.com/uc?export=view&id=1yKDAR4DLEmeRrAfLquit-jqtusBeB5PT",
    ],
  },
  {
    title: "HOTEL SEMIRAMIS W TANZANII",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1aSgRUN8je09GihIQy9YfnUPCTsgYJaQs",
      "http://drive.google.com/uc?export=view&id=14H-W5VxDTOOzR3LnJ3hwyFEM-I2W-uxw",
      "http://drive.google.com/uc?export=view&id=19DpuH0yN26Hts5ohxhHdu059r6t5QS-Y",
      "http://drive.google.com/uc?export=view&id=19TbKaHXV-wGLdCdt4tOIvtFEvfVI03z8",
      "http://drive.google.com/uc?export=view&id=1GO7X89b_Bn9FepEDYtAT-A7WS8MsqOyi",
      "http://drive.google.com/uc?export=view&id=1M5f2kttIeLcKAcOb2MGqgTKtfQKBOcvr",
      "http://drive.google.com/uc?export=view&id=1YZoZJTv83rLCIkMS7_irSpWVs5MChjdU",
      "http://drive.google.com/uc?export=view&id=1ZuHzsGthRXaNZUis6CyJmAYxynVnjs49",
      "http://drive.google.com/uc?export=view&id=1gg3uVex2QD5S_Gp7dX7oUPPZ9b9_7MQo",
      "http://drive.google.com/uc?export=view&id=1hYRroRlBIGOYwPSg2ovU5Z237QcsboGq",
      "http://drive.google.com/uc?export=view&id=1jFzbtCw4HdXJM9k0WqSLu6WlRB2Y2vJG",
      "http://drive.google.com/uc?export=view&id=1kvqeG02N7GWNCygjFZlAhCSKmOyrXRHK",
      "http://drive.google.com/uc?export=view&id=1mk8X_i50XIx6ScctCzIiV_LrLjAicKdv",
      "http://drive.google.com/uc?export=view&id=1nVptD66RM-PeTTVI-3JNGD6JXRaYIW3Y",
      "http://drive.google.com/uc?export=view&id=1oAFROUHIkcXMEKtze9pcUGBI7Cw2leYF",
      "http://drive.google.com/uc?export=view&id=1oDAaaf5iI8rG41JPqOYe4LfTdbiEz7k9",
      "http://drive.google.com/uc?export=view&id=1rX7X4LT-4AWLwiYRD6hZVWV0Y_ysEhI5",
      "http://drive.google.com/uc?export=view&id=1sw7LJBhuUCFFoRNGVZpBMx5aCOIx8s50",
      "http://drive.google.com/uc?export=view&id=1uU1W19ZuIR_UOxCZvaTBnALNET_DqVYE",
      "http://drive.google.com/uc?export=view&id=1vO24t8TGPUHfGNzIRl2l9IJ0PmfJxJqn",
    ],
  },
  {
    title: "BUDYNEK WIELORODZINNY W KRAKOWIE NA UL. KOBIERZYŃSKIEJ",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1zQsSvtvsovJLvrT0cy_mAIGy8sHxldo6",
      "http://drive.google.com/uc?export=view&id=1o52OuABpmMoUgxJVdKYoJCg264l7BAT2",
      "http://drive.google.com/uc?export=view&id=1ldlyEUvB7yJ4LygrSo4BG4axE3OhwP6e",
      "http://drive.google.com/uc?export=view&id=1TXwVkgUgLorWThJT03bI5yTiZrF3xFsg",
      "http://drive.google.com/uc?export=view&id=1RdmJVJGLE7UdgGb8gqhCbmJc7nv2XpE7",
      "http://drive.google.com/uc?export=view&id=1M5Cf9hmZADf0nR5qdLAZ7Rf4EW77BpOI",
      "http://drive.google.com/uc?export=view&id=1FzXpn69VYMlhbXl12jO1P8d-XQWlcfWW",
      "http://drive.google.com/uc?export=view&id=1Ef9s8iYdPfv5oYTzEE3foT3VgkU3Am_4",
      "http://drive.google.com/uc?export=view&id=1E2OCX2aP9x9gJ3eLqKOSBjapAhUi4-kL",
    ],
  },
  {
    title: "KONCEPCJA PAWILONU WEJŚCIOWEGO W PARKU MINIATUR W ZABIERZOWIE",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1KAyafCUj0kwOIJOIrHGwUi-sRRsz0qAf",
      "http://drive.google.com/uc?export=view&id=13UJT1vVdUP9I19IttDnXWeKLK-U_jiT0",
      "http://drive.google.com/uc?export=view&id=1I7nPxWsRtajvsKfPHqU9DC5kZs97iKfU",
      "http://drive.google.com/uc?export=view&id=1OaVtN0_0EXZ__FuDKrBgfsT2VXWtr_ce",
      "http://drive.google.com/uc?export=view&id=1xBcWR95GpmzbP5Ik14N82a_MPCV8EsnQ",
    ],
  },
  {
    title: "BUDYNEK JEDNORODZINNY NA ULICY TYNIECKIEJ W KRAKOWIE",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1s0ZTmuytsJnm9lHRTzd1Ed4FMDb11Vh8",
      "http://drive.google.com/uc?export=view&id=1iwJ858kJUW3u6hRz4H4xfdX9SCwD-4AX",
      "http://drive.google.com/uc?export=view&id=1gOM_k02Qn_E5jx6QNfFHmGsinWiDEPFq",
    ],
  },
  {
    title: "MODUŁOWY BUDYNEK LETNISKOWY W CHORWACJI",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1AwY4emr6nMHd3JH3Vh4FDloUliEzYrQZ",
      "http://drive.google.com/uc?export=view&id=11jUDB6ctv4ueBZBddEq66o1mDh6VuWha",
      "http://drive.google.com/uc?export=view&id=11UgrRa-_dsEUHdpTMG68DUQDZyBRCF7I",
      "http://drive.google.com/uc?export=view&id=1YOqBZc2PnrnA6yovHDCknIHbz33Mjfxl",
      "http://drive.google.com/uc?export=view&id=1YbyyNdTicqquYrifRBH8_opAVBr48tfQ",
    ],
  },

  {
    title: "KIOSKI HANDLOWE W HAMBURGU",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=16lqCuyBmHjmjOiMUlsZfK6yhcccvimqq",
      "http://drive.google.com/uc?export=view&id=1vMRdSL0hj_opVCtW1wWjTQQY3ikKRE4C",
      "http://drive.google.com/uc?export=view&id=10swxN_FXaizGZUYbEwMhzplDc19Q_hdb",
    ],
  },
  {
    title: "ZESPÓŁ BUDYNKÓW WIELORODZINNYCH W KONINIE ŻEGAŃSKIM",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1jSz7SZSAcd-Q1m2SNSsI65jUkLUrDsd4",
      "http://drive.google.com/uc?export=view&id=16gWIFoLYmEFbY2Ztuh0eHZBwj78n8wMZ",
      "http://drive.google.com/uc?export=view&id=1cyZGJILS8srqG0Oi7l9uxOknIXc-VIk5",
      "http://drive.google.com/uc?export=view&id=1hPa-ywR0N6SsKIJQXeEBmQLjkCSuDn1C",
      "http://drive.google.com/uc?export=view&id=1uOkenB9tjso3_kADzUWcaGRegKQtH1ok",
      "http://drive.google.com/uc?export=view&id=1zdQUZY7tlLh585z1_Vtkj7FM-N1mhG7M",
    ],
  },
  {
    title: "MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=11oPCNVEu7aNgd4K6_DFEGJvmrdSCsqnw",
      "http://drive.google.com/uc?export=view&id=1JLGXw5d1gv-Qq0T6tPlD3DTgxfLqLW_w",
      "http://drive.google.com/uc?export=view&id=1RXgIXOymHghxfMxGuqEp0o0xaSMXgJqy",
      "http://drive.google.com/uc?export=view&id=1XDpbKv5guzR2iWCHbfDLpHm4yovdxkN8",
      "http://drive.google.com/uc?export=view&id=1aWCKkO_dC3joY5p4Dzvp2gb5czM358ES",
      "http://drive.google.com/uc?export=view&id=1b6SxsEDMYVQGWDOLYm6vmN7ofxHBy8oa",
      "http://drive.google.com/uc?export=view&id=1e9D1IflLyaVMXz7TY3EP7x2RTbahAvvr",
      "http://drive.google.com/uc?export=view&id=1h5FJ2sDEMheYpF9FSLA8z8jwV1NRRGV9",
      "http://drive.google.com/uc?export=view&id=1l_kwmgrFc7AbYZsLDsBBtO0lEnaZbkFo",
      "http://drive.google.com/uc?export=view&id=1n4cm-XpzCFAYyRc13vh9sKXphLaAWNrF",
      "http://drive.google.com/uc?export=view&id=1oIh1SRiOQtXZywcLaEcFYIzQHhQDHooM",
      "http://drive.google.com/uc?export=view&id=1oYIksukY88fmYklBiFuEb4k09C6LIuvN",
      "http://drive.google.com/uc?export=view&id=1sDHbGSmzB_2KoGA8mmpvgy2jN6dp4zCu",
      "http://drive.google.com/uc?export=view&id=1vB839WG-z3nhVd4SuRV_TBf88VkmVbdb",
      "http://drive.google.com/uc?export=view&id=19c9CEFeMUKFM50I7RnH_BcrRhPBURepk",
      "http://drive.google.com/uc?export=view&id=1CdJJqzN0NvVclttyMSf4HsNHWsJkKkR6",
    ],
  },
  {
    title: "KONCEPCJA BUDYNKU BIUROWEGO PZU W ŁODZI",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1ZJACLCHLXwph6tLCk1rDAODDrkLyB9mt",
      "http://drive.google.com/uc?export=view&id=1babtoT0xdKGNbA_xDxrDqbQl7ym1_-mP",
      "http://drive.google.com/uc?export=view&id=1tICNmcG8qtJSzv-EgsqQil7luxvx1a1c",
    ],
  },
  {
    title: "KONCEPCJA PAWILONU GASTRONOMICZNEGO W RUDAWIE",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=163-wvHCPI3ZQXqUcF6kPPiUiFPVgjikX",
      "http://drive.google.com/uc?export=view&id=1APDEWgy_uNSRFyuZVddn8X4X0oVo3q3t",
      "http://drive.google.com/uc?export=view&id=1FOMP0VYfLHihtLOTeSdP07IUr3xdQMft",
      "http://drive.google.com/uc?export=view&id=1JlIRQJyfhyuK8fxCNLEQR3il_jmKvMz8",
      "http://drive.google.com/uc?export=view&id=1LODvmkM5HWd1c727zbjqBUxnHufZPGfW",
    ],
  },
  {
    title: "KONCEPCJA HOTELI NA WODZIE W ROŻNOWIE",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1XUtZoDWwJqCrThE8vaSY9QzKDefZpIgR",
      "http://drive.google.com/uc?export=view&id=1rYfPea3EknV7rOeuJXvtq2F0uuptxD4q",
      "http://drive.google.com/uc?export=view&id=1-ZrAlakV_JjKwUxeuyDo6YJq1ICSFXvQ",
      "http://drive.google.com/uc?export=view&id=1w0rZXAuvjW20NXaIgCbHkAVyX6FF-jSz",
      "http://drive.google.com/uc?export=view&id=1wBTvL9rem5vyT66xJ2W6OtUv1Er4j918",
    ],
  },

  {
    title: "BIUROWIEC QMODULAR W WĘGRZCACH WIELKICH",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1FLi28g2RC2expd1DctixytOjInC6IFgX",
      "http://drive.google.com/uc?export=view&id=1-GuYaHq661LBovgV36QvD57y_D9cTFEw",
      "http://drive.google.com/uc?export=view&id=1OgtxqdVLwmGRbsy5yB4WeedgiJz4P-jR",
      "http://drive.google.com/uc?export=view&id=1RCKNVGp9EBrcyFkX831jPWLcnOeUzApy",
    ],
  },

  {
    title: "DOM JEDNORODZINNY W BIAŁEJ RAWSKIEJ",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1kkZMxZI4jor-o51AVCx5vaxe9vd0thXe",
      "http://drive.google.com/uc?export=view&id=1qXXq-EphAPdJ0ozPYTT8NUtR3nYnVI4h",
      "http://drive.google.com/uc?export=view&id=11haljaGngQYKB4vSbMES1V0aNdx01I_Z",
      "http://drive.google.com/uc?export=view&id=17CoDsb0OHLskYW6_-sn9Nd9AoLvEXU-g",
      "http://drive.google.com/uc?export=view&id=1aztYpAcU6lsLZWwP2qy6jPEVAS8F55oZ",
      "http://drive.google.com/uc?export=view&id=1e5my2i9OxJMj0xGWpsWm9t8RLRQs1U5F",
      "http://drive.google.com/uc?export=view&id=1_HAlp4EnUyM0TkdMeH9AdBGCZsADamnt",
      "http://drive.google.com/uc?export=view&id=1-YirF4YEmy44ghVNhl0pOmrhp-V13Wvh",
      "http://drive.google.com/uc?export=view&id=1xGDji0s-D-121QrmlvaPDeAZGbC499u7",
    ],
  },

  {
    title: "DOM JEDNORODZINNY - 23L1",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1ZoMvDi2PMTLdjJf0KXW-OXzLqPuOODgm",
      "http://drive.google.com/uc?export=view&id=1bYSm-djDS_MWEwWhU7crJg3bIYobl5Vf",
      "http://drive.google.com/uc?export=view&id=1bxkViLzuVdkf_0D6mfDmH4a9V0NqhJhS",
      "http://drive.google.com/uc?export=view&id=1jwg_a1UceoLy5L619Es0MGJNlds5Fw7f",
      "http://drive.google.com/uc?export=view&id=1rR0JAlCfpBPdJhFlj7DMgGgj1qPzROJf",
      "http://drive.google.com/uc?export=view&id=1r_Or_EmDjTlO261HVRXNb2UlcG5KnVo3",
      "http://drive.google.com/uc?export=view&id=1tMq-UDM9mOfruQOQFLXdKLrDeW4gajm7",
    ],
  },
  {
    title: "DOM JEDNORODZINNY - 23L2",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1GA0rYc7nY_yT4wZjUod38IYUgGsuba-P",
      "http://drive.google.com/uc?export=view&id=10m69txDLeI5DnL7li7FcfSK-VPVNftFG",
      "http://drive.google.com/uc?export=view&id=1LGi296aRVEUvVZlOtwiqHEinHA6cwhzU",
      "http://drive.google.com/uc?export=view&id=1U4KpsvKTGc2F0ycuByeWQo40By6yvZ8U",
      "http://drive.google.com/uc?export=view&id=1Znc0kXbDtOvxjvkahZRQnmSgGr_8Wr8Q",
      "http://drive.google.com/uc?export=view&id=1ZxVN6gbzbZ8fJE9E806nhWAxjcMTFeXe",
      "http://drive.google.com/uc?export=view&id=1eZ1IBLwQuFfiW6OpAgpHj1R0UqeXyS0p",
      "http://drive.google.com/uc?export=view&id=1iPzTwz8z6LQMZuwyV5d10V9WxIQ00J4d",
      "http://drive.google.com/uc?export=view&id=1mAbDDXqTrS8cFw0nBdHC93I9ctza8-qA",
      "http://drive.google.com/uc?export=view&id=1vXqgV0pWWFI_8LVMxWZpeCLbu0DzIaIJ",
    ],
  },
  {
    title: "DOM JEDNORODZINNY - 23P1",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=15BA5GYkcGuFPUZwLkEO-Ju8-gdPOYsb3",
      "http://drive.google.com/uc?export=view&id=1IRiTNQh2a-xgrmQoDUQnj5Oe3AxU6Q93",
      "http://drive.google.com/uc?export=view&id=1XCSfwGN0Tw__FCpNDOKhsYFtd6hQWy7y",
      "http://drive.google.com/uc?export=view&id=1YJwONGnfW4xI54LZv0bPfIzfIw86hiQF",
      "http://drive.google.com/uc?export=view&id=1hVWWsSJH9v5nvBV7uccrsQ32KCDAovyJ",
      "http://drive.google.com/uc?export=view&id=1rOrPUnDFBYkP5JhMcjIepZfT7GuZ1sSW",
    ],
  },
  {
    title: "DOM JEDNORODZINNY - 23P2",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1xqhJaPXSfTYgHVXVd5upxvrcLxAL4SdH",
      "http://drive.google.com/uc?export=view&id=1wRr-doQPArVgXsfIMqa2MYh4WERM7WpC",
      "http://drive.google.com/uc?export=view&id=1tkIoAQJI3FrcCJ9uzIaQzQ2luihSDrBj",
      "http://drive.google.com/uc?export=view&id=1SY98RYy8MlkVeEJRYHEZc_o2SF6Z9tSU",
      "http://drive.google.com/uc?export=view&id=1HahAuZzypSjVY0PoW9K5HWLasjdSkabv",
      "http://drive.google.com/uc?export=view&id=1BjBkoqrluyW4Nduat1LyhP4xDDkI3xRe",
    ],
  },
  {
    title: "DOM JEDNORODZINNY - 23X1",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1D5kfUPaQmKCa6G4xVfLU2i8NeNiEgAMl",
      "http://drive.google.com/uc?export=view&id=1_5DcewY9kAjqUP-jKDwSrQzqTxYA0U9_",
      "http://drive.google.com/uc?export=view&id=1avfdOVp5lLc5R5IuQm3arwsDz_HGRa3K",
      "http://drive.google.com/uc?export=view&id=1dekA-SJDJo2Zm2v6cwlxjzuR1ynaALhS",
      "http://drive.google.com/uc?export=view&id=1y8CcuefRDZUW4JOOX0Cw_XSVn5hY5BHe",
      "http://drive.google.com/uc?export=view&id=1-5IZqVjx3qhusdCjiBLULwHp-raLmnqs",
    ],
  },
  {
    title: "DOM JEDNORODZINNY - 23Z1",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1c5JQqS6H8a4Pwe1FZE-oBa0g-4ogGoq3",
      "http://drive.google.com/uc?export=view&id=1MLaZN_FBbiVoZNI3jmEmZM8iXKBbm5r_",
      "http://drive.google.com/uc?export=view&id=1nbk0GZx_JMzJijn7KEV04QONVlMqaYOj",
      "http://drive.google.com/uc?export=view&id=1O3rvjaPO5grj_gZQ4wdPVQF5541E8n4Y",
      "http://drive.google.com/uc?export=view&id=1x2WUR6inWczgnB5GoZh9VFml-k50GvdG",
      "http://drive.google.com/uc?export=view&id=17h7Mch9lwTnWp73HB9gCpydJCa6pms5-",
    ],
  },
  {
    title: "DOM JEDNORODZINNY - 23Z2",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=1KshdaJAiTh3SHzUX8O0XgevCSqPTuXRO",
      "http://drive.google.com/uc?export=view&id=1dRhdNiiOaKNj7pZsYn1d5XjVlfXTLbaF",
      "http://drive.google.com/uc?export=view&id=1u2yLwwV27pEvWjl6jY5GcTtWyqHR1KJn",
      "http://drive.google.com/uc?export=view&id=1a662-L53AiL_XTU29G4MoaL7DOmwffuh",
    ],
  },
];

const iconsData = [
  {
    title: "PROJEKTY INDYWIDUALNE",
    description: "",
    path: "/icons/projekty-indywidualne.png",
  },
  {
    title: "ANALIZA DZIAŁKI",
    description: "",
    path: "/icons/analiza.png",
  },
  {
    title: "BUDOWNICTWO MODUŁOWE",
    description: "",
    path: "/icons/bud-modulowe.png",
  },
  {
    title: "BUDOWNICTWO PASYWNE",
    description: "",
    path: "/icons/bud-pasywne.png",
  },
  {
    title: "CHMURA PUNKTÓW",
    description: "",
    path: "/icons/chmura-punktow.png",
  },
  {
    title: "PROJEKTOWANIE BIM",
    description: "",
    path: "/icons/projektowanie-bim.png",
  },

  {
    title: "PROJEKTY WNĘTRZ",
    description: "",
    path: "/icons/projekty-wnetrz.png",
  },
  {
    title: "WIZUALIZACJE I ANIMACJE",
    description: "",
    path: "/icons/wizualizacje-animacje.png",
  },
];

export { projectsData, iconsData };
