const projectsData = [
  {
    title: "HOTEL W UŚCIU GORLICKIM",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "http://drive.google.com/uc?export=view&id=199nVosWkwZgyPwjJdL4VzIDE1g9-f-ES",
      "http://drive.google.com/uc?export=view&id=105xQyORtcvQ10ad4KP4iDVNxrWPif2ZN",
      "http://drive.google.com/uc?export=view&id=1IYXkPKEB94xsUxjk4v9ngmTjFR0MWeoh",
      "http://drive.google.com/uc?export=view&id=1YZYO_432IvYApa09wjmwKH-bnlL3EzCR",
    ],

    
    
    
     
  },
  {
    title: "REZYDENCJA W TANZANII",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [

      "http://drive.google.com/uc?export=view&id=13COFz51ev94mExSHDBeQO41gZ2VZK5bY",
      "http://drive.google.com/uc?export=view&id=11pkiz6ExWiQ-ftZJWakYkmvfuilPRpBf",
      "http://drive.google.com/uc?export=view&id=17LObnRMQ5BJtjmJmWIVJixHpbtnpzojl ",
      "http://drive.google.com/uc?export=view&id=19zuUlS0TomM0mDyZk_iYBVvNruz365XL ",
      "http://drive.google.com/uc?export=view&id=1OKWIjxjwiH7NxN7B8lATYa3pByn0nSGC",
      "http://drive.google.com/uc?export=view&id=1PVeg4oAs3eFtSFa5H4_yZfRQ1c1R_hLA ",
      "http://drive.google.com/uc?export=view&id=1YS5Qa1u1lICAASSNvOs0YWeCmDy8R8QN",
      "http://drive.google.com/uc?export=view&id=1k2AGZJPgw0xRaFoI6FTQH6lBPri76BTj",
      "http://drive.google.com/uc?export=view&id=1yKDAR4DLEmeRrAfLquit-jqtusBeB5PT",
    ]
  },
  {
    title: "HOTEL SEMIRAMIS W TANZANII",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/1.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/2.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/3.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/4.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/5.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/6.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/7.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/8.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/9.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/10.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/11.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/12.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/13.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/14.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/15.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/16.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/17.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/18.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/19.jpg",
      "/strona-www/3_HOTEL SEMIRAMIS W TANZANII/20.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "BUDYNEK WIELORODZINNY W KRAKOWIE NA UL. KOBIERZYŃSKIEJ",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/4_BUDYNEK WIELORODZINNY W KRAKOWIE NA ULICY KOBIERZYŃSKIEJ/1.jpg",
      "/strona-www/4_BUDYNEK WIELORODZINNY W KRAKOWIE NA ULICY KOBIERZYŃSKIEJ/2.jpg",
      "/strona-www/4_BUDYNEK WIELORODZINNY W KRAKOWIE NA ULICY KOBIERZYŃSKIEJ/3.jpg",
      "/strona-www/4_BUDYNEK WIELORODZINNY W KRAKOWIE NA ULICY KOBIERZYŃSKIEJ/4.jpg",
      "/strona-www/4_BUDYNEK WIELORODZINNY W KRAKOWIE NA ULICY KOBIERZYŃSKIEJ/5.jpg",
      "/strona-www/4_BUDYNEK WIELORODZINNY W KRAKOWIE NA ULICY KOBIERZYŃSKIEJ/6.jpg",
      "/strona-www/4_BUDYNEK WIELORODZINNY W KRAKOWIE NA ULICY KOBIERZYŃSKIEJ/7.jpg",
      "/strona-www/4_BUDYNEK WIELORODZINNY W KRAKOWIE NA ULICY KOBIERZYŃSKIEJ/8.jpg",
      "/strona-www/4_BUDYNEK WIELORODZINNY W KRAKOWIE NA ULICY KOBIERZYŃSKIEJ/9.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "KONCEPCJA PAWILONU WEJŚCIOWEGO W PARKU MINIATUR W ZABIERZOWIE",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/5_KONCEPCJA PAWILONU WEJŚCIOWEGO W PARKU MINIATUR W ZABIERZOWIE/1.jpg",
      "/strona-www/5_KONCEPCJA PAWILONU WEJŚCIOWEGO W PARKU MINIATUR W ZABIERZOWIE/2.jpg",
      "/strona-www/5_KONCEPCJA PAWILONU WEJŚCIOWEGO W PARKU MINIATUR W ZABIERZOWIE/3.jpg",
      "/strona-www/5_KONCEPCJA PAWILONU WEJŚCIOWEGO W PARKU MINIATUR W ZABIERZOWIE/4.jpg",
      "/strona-www/5_KONCEPCJA PAWILONU WEJŚCIOWEGO W PARKU MINIATUR W ZABIERZOWIE/5.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "BUDYNEK JEDNORODZINNY NA ULICY TYNIECKIEJ W KRAKOWIE",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/7_BUDYNEK JEDNORODZINNY NA ULICY TYNIECKIEJ W KRAKOWIE/1.jpg",
      "/strona-www/7_BUDYNEK JEDNORODZINNY NA ULICY TYNIECKIEJ W KRAKOWIE/2.jpg",
      "/strona-www/7_BUDYNEK JEDNORODZINNY NA ULICY TYNIECKIEJ W KRAKOWIE/3.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "MODUŁOWY BUDYNEK LETNISKOWY W CHORWACJI",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/8_MODUŁOWY BUDYNEK LETNISKOWY W CHORWACJI/1.jpg",
      "/strona-www/8_MODUŁOWY BUDYNEK LETNISKOWY W CHORWACJI/2.jpg",
      "/strona-www/8_MODUŁOWY BUDYNEK LETNISKOWY W CHORWACJI/3.jpg",
      "/strona-www/8_MODUŁOWY BUDYNEK LETNISKOWY W CHORWACJI/4.jpg",
      "/strona-www/8_MODUŁOWY BUDYNEK LETNISKOWY W CHORWACJI/5.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },

  {
    title: "KIOSKI HANDLOWE ORAZ GASTRONOMICZNE W BERLINIE",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/9_KIOSKI HANDLOWE ORAZ GASTRONOMICZNE W BERLINIE/1.jpg",
      "/strona-www/9_KIOSKI HANDLOWE ORAZ GASTRONOMICZNE W BERLINIE/2.jpg",
      "/strona-www/9_KIOSKI HANDLOWE ORAZ GASTRONOMICZNE W BERLINIE/3.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",

    ],
  },
  {
    title: "ZESPÓŁ BUDYNKÓW WIELORODZINNYCH W KONINIE ŻEGAŃSKIM",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/10_ZESPÓŁ BUDYNKÓW WIELORODZINNYCH W KONINIE ŻEGAŃSKIM/1.jpg",
      "/strona-www/10_ZESPÓŁ BUDYNKÓW WIELORODZINNYCH W KONINIE ŻEGAŃSKIM/2.jpg",
      "/strona-www/10_ZESPÓŁ BUDYNKÓW WIELORODZINNYCH W KONINIE ŻEGAŃSKIM/3.jpg",
      "/strona-www/10_ZESPÓŁ BUDYNKÓW WIELORODZINNYCH W KONINIE ŻEGAŃSKIM/4.jpg",
      "/strona-www/10_ZESPÓŁ BUDYNKÓW WIELORODZINNYCH W KONINIE ŻEGAŃSKIM/5.jpg",
      "/strona-www/10_ZESPÓŁ BUDYNKÓW WIELORODZINNYCH W KONINIE ŻEGAŃSKIM/6.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/1.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/2.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/3.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/4.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/5.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/6.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/7.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/8.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/9.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/10.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/11.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/12.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/13.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/14.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/15.jpg",
      "/strona-www/11_MODULARCITY - KONCEPCJA HOTELI MODUŁOWYCH/16.jpg",
      
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "KONCEPCJA BUDYNKU BIUROWEGO PZU W ŁODZI",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/12_KONCEPCJA BUDYNKU BIUROWEGO PZU W ŁODZI/1.jpg",
      "/strona-www/12_KONCEPCJA BUDYNKU BIUROWEGO PZU W ŁODZI/2.jpg",
      "/strona-www/12_KONCEPCJA BUDYNKU BIUROWEGO PZU W ŁODZI/3.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "KONCEPCJA PAWILONU GASTRONOMICZNEGO W RUDAWIE",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/13_KONCEPCJA PAWILONU GASTRONOMICZNEGO W RUDAWIE/1.jpg",
      "/strona-www/13_KONCEPCJA PAWILONU GASTRONOMICZNEGO W RUDAWIE/2.jpg",
      "/strona-www/13_KONCEPCJA PAWILONU GASTRONOMICZNEGO W RUDAWIE/3.jpg",
      "/strona-www/13_KONCEPCJA PAWILONU GASTRONOMICZNEGO W RUDAWIE/4.jpg",
      "/strona-www/13_KONCEPCJA PAWILONU GASTRONOMICZNEGO W RUDAWIE/5.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "KONCEPCJA HOTELI NA WODZIE W ROŻOWIE",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/14_KONCEPCJA HOTELI NA WODZIE W ROŻOWIE/1.jpg",
      "/strona-www/14_KONCEPCJA HOTELI NA WODZIE W ROŻOWIE/2.jpg",
      "/strona-www/14_KONCEPCJA HOTELI NA WODZIE W ROŻOWIE/3.jpg",
      "/strona-www/14_KONCEPCJA HOTELI NA WODZIE W ROŻOWIE/4.jpg",
      "/strona-www/14_KONCEPCJA HOTELI NA WODZIE W ROŻOWIE/5.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },

  {
    title: "DOM JEDNORODZINNY - 23L1",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/DOM JEDNORODZINNY - 23L1/1.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L1/2.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L1/3.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L1/4.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L1/5.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L1/6.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L1/7.jpg",
      
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "DOM JEDNORODZINNY - 23L2",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/DOM JEDNORODZINNY - 23L2/1.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L2/2.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L2/3.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L2/4.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L2/5.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L2/6.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L2/7.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L2/8.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L2/9.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23L2/10.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "DOM JEDNORODZINNY - 23P1",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/DOM JEDNORODZINNY - 23P1/1.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23P1/2.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23P1/3.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23P1/4.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23P1/5.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23P1/6.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "DOM JEDNORODZINNY - 23P2",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/DOM JEDNORODZINNY - 23P2/1.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23P2/2.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23P2/3.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23P2/4.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23P2/4.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23P2/6.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "DOM JEDNORODZINNY - 23X1",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/DOM JEDNORODZINNY - 23X1/1.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23X1/2.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23X1/3.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23X1/4.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23X1/5.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23X1/6.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "DOM JEDNORODZINNY - 23Z1",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/DOM JEDNORODZINNY - 23Z1/1.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23Z1/2.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23Z1/3.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23Z1/4.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23Z1/5.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23Z1/6.jpg",
      
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
  {
    title: "DOM JEDNORODZINNY - 23Z2",
    content: "Jest to projekt hotelu w uściu gorlickim",
    images: [
      "/strona-www/DOM JEDNORODZINNY - 23Z2/1.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23Z2/2.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23Z2/3.jpg",
      "/strona-www/DOM JEDNORODZINNY - 23Z2/4.jpg",

      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
      "http://drive.google.com/uc?export=view&id=",
    ],
  },
];

const iconsData = [
  {
    title: "PROJEKTY INDYWIDUALNE",
    description: "",
    path: "/icons/projekty-indywidualne.png",
  },
  {
    title: "ANALIZA DZIAŁKI",
    description: "",
    path: "/icons/analiza.png",
  },
  {
    title: "BUDOWNICTWO MODUŁOWE",
    description: "",
    path: "/icons/bud-modulowe.png",
  },
  {
    title: "BUDOWNICTWO PASYWNE",
    description: "",
    path: "/icons/bud-pasywne.png",
  },
  {
    title: "CHMURA PUNKTÓW",
    description: "",
    path: "/icons/chmura-punktow.png",
  },
  {
    title: "PROJEKTOWANIE BIM",
    description: "",
    path: "/icons/projektowanie-bim.png",
  },

  {
    title: "PROJEKTY WNĘTRZ",
    description: "",
    path: "/icons/projekty-wnetrz.png",
  },
  {
    title: "WIZUALIZACJE I ANIMACJE",
    description: "",
    path: "/icons/wizualizacje-animacje.png",
  },
];

export { projectsData, iconsData };
